description: COLDA PROJECT Data Caalog
sources:
  project_atlantic_var:
    args:
      path: '{{CATALOG_DIR}}/project_atlantic_var.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}
  project_land:
    args:
      path: '{{CATALOG_DIR}}/project_land.yaml'
    description: ''
    driver: intake.catalog.local.YAMLFileCatalog
    metadata: {}
